import { Poppins } from "next/font/google";
import Sidebar from "../components/ui/sidebar";
import MobileNav from "../components/ui/mobile-nav";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Efandex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}>
        <div className="flex min-h-screen">
          {/* Sidebar for Desktop */}
          <div className="w-[280px] h-screen fixed top-0 left-0 bg-white shadow-lg lg:block hidden">
            <Sidebar />
          </div>

          {/* Main content area */}
          <div className="flex-1 lg:ml-[280px] flex flex-col">
            {/* Mobile navigation for smaller screens */}
            <div className="lg:hidden">
              <MobileNav />
            </div>

            {/* Main content */}
            <main className="flex-1 overflow-y-auto bg-[#FAFCFF]">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
